import { NextResponse } from 'next/server'
import { ZoneRenewalWithQuotes } from '@/lib/types/database'

// Sample data based on the screenshot
const sampleRenewals: ZoneRenewalWithQuotes[] = [
  {
    policy_id: 'DANPARKPTY',
    client_code: 'DANPARKPTY',
    client_name: 'DANPARK PTY LTD',
    lob: 'Business Pack',
    expiry_date: '2026-01-10',
    invoice_total: 8833,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'DANPARKPTY',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 1,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [
      {
        id: 1,
        policy_id: 'DANPARKPTY',
        class: 'Business Pack',
        insurer: 'CGU Insurance',
        premium: 7800,
        broker_fee: 1033,
        comments: 'Competitive rate, includes cyber coverage',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  },
  {
    policy_id: 'KUATROBUIL-1',
    client_code: 'KUATROBUIL',
    client_name: 'KUATRO BUILDING CONTRACTORS',
    lob: 'Contracts Works - Single Contract',
    expiry_date: '2026-01-25',
    invoice_total: 457929.03,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'KUATROBUIL',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 2,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [],
  },
  {
    policy_id: 'SP10868',
    client_code: 'SP10868',
    client_name: 'STRATA PLAN 10868',
    lob: 'Strata Title Insurance',
    expiry_date: '2026-02-15',
    invoice_total: null,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'SP10868',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 3,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [],
  },
  {
    policy_id: 'MAANENBERI',
    client_code: 'MAANENBERI',
    client_name: 'MAANEN & BERISHAJ',
    lob: 'Home and Contents',
    expiry_date: '2026-03-05',
    invoice_total: 2862.97,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'MAANENBERI',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 4,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [],
  },
  {
    policy_id: 'SP68259',
    client_code: 'SP68259',
    client_name: 'STRATA PLAN 68259',
    lob: 'Strata Title Insurance',
    expiry_date: '2026-01-15',
    invoice_total: null,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'SP68259',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 5,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [],
  },
  {
    policy_id: 'SP10428',
    client_code: 'SP10428',
    client_name: 'STRATA PLAN 10428',
    lob: 'Strata Title Insurance',
    expiry_date: '2026-02-28',
    invoice_total: null,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'SP10428',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 6,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [],
  },
  {
    policy_id: 'SP17823',
    client_code: 'SP17823',
    client_name: 'STRATA PLAN 17823',
    lob: 'Strata Title Insurance',
    expiry_date: '2026-03-20',
    invoice_total: null,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'SP17823',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 7,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [],
  },
  {
    policy_id: 'SP78081',
    client_code: 'SP78081',
    client_name: 'STRATA PLAN 78081',
    lob: 'Strata Title Insurance',
    expiry_date: '2026-04-10',
    invoice_total: null,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'SP78081',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 8,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [],
  },
  {
    policy_id: 'FOOTNOTES1-1',
    client_code: 'FOOTNOTES1',
    client_name: 'FOOTNOTES COMMUNICATIONS',
    lob: 'Combined Broadform Liability & Prof Indemnity',
    expiry_date: '2026-02-08',
    invoice_total: null,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'FOOTNOTES1',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 9,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [],
  },
  {
    policy_id: 'FOOTNOTES1-2',
    client_code: 'FOOTNOTES1',
    client_name: 'FOOTNOTES COMMUNICATIONS',
    lob: 'Cyber Liability',
    expiry_date: '2026-02-08',
    invoice_total: null,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'FOOTNOTES1',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 10,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [],
  },
  {
    policy_id: 'FOOTNOTES1-3',
    client_code: 'FOOTNOTES1',
    client_name: 'FOOTNOTES COMMUNICATIONS',
    lob: 'Liability Insurance',
    expiry_date: '2026-02-08',
    invoice_total: null,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'FOOTNOTES1',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 11,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [],
  },
  {
    policy_id: 'NORTHEAST-1',
    client_code: 'NORTHEAST',
    client_name: 'NORTHEAST INSURANCE BROKERS',
    lob: 'Business Insurance',
    expiry_date: '2026-01-08',
    invoice_total: 6537.37,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'NORTHEAST',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 12,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [
      {
        id: 2,
        policy_id: 'NORTHEAST-1',
        class: 'Business Insurance',
        insurer: 'QBE Insurance',
        premium: 5850,
        broker_fee: 687.37,
        comments: 'Best quote received',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 3,
        policy_id: 'NORTHEAST-1',
        class: 'Business Insurance',
        insurer: 'Allianz',
        premium: 6200,
        broker_fee: 720,
        comments: 'Higher premium but better coverage',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
  },
  {
    policy_id: 'NORTHEAST-2',
    client_code: 'NORTHEAST',
    client_name: 'NORTHEAST INSURANCE BROKERS',
    lob: 'COMMERCIAL MOTOR',
    expiry_date: '2026-01-08',
    invoice_total: 5876.63,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'NORTHEAST',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 13,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [],
  },
  {
    policy_id: 'NORTHEAST-3',
    client_code: 'NORTHEAST',
    client_name: 'NORTHEAST INSURANCE BROKERS',
    lob: 'General Property',
    expiry_date: '2026-01-08',
    invoice_total: 3343.36,
    renewal_colour: 'yellow',
    marked_for_deletion: false,
    status: 'pending',
    notes: null,
    account_manager: null,
    client_group: null,
    inception_date: null,
    zone: null,
    ledger: null,
    client_id: 'NORTHEAST',
    client_group_id: null,
    account_manager_id: null,
    underwriter_name: null,
    underwriter_id: null,
    renewal_order: 14,
    client_info: null,
    policy_number: null,
    transaction_type: null,
    revenue: null,
    marked_for_deletion_at: null,
    marked_for_deletion_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    quotes: [],
  },
]

/**
 * GET /api/renewals
 * Returns sample renewals data
 */
export async function GET() {
  try {
    // Return sample data
    return NextResponse.json({ data: sampleRenewals })
  } catch (error) {
    console.error('Unexpected error:', error)
    return NextResponse.json(
      { error: 'Unexpected error', details: error },
      { status: 500 }
    )
  }
}

/**
 * PATCH /api/renewals
 * Update a renewal's marked_for_deletion status or notes
 */
export async function PATCH(request: Request) {
  try {
    const body = await request.json()
    const { policy_id, marked_for_deletion, notes } = body

    if (!policy_id) {
      return NextResponse.json(
        { error: 'policy_id is required' },
        { status: 400 }
      )
    }

    // Find the renewal in sample data
    const renewal = sampleRenewals.find((r) => r.policy_id === policy_id)

    if (!renewal) {
      return NextResponse.json(
        { error: 'Renewal not found' },
        { status: 404 }
      )
    }

    // Update in-memory data
    if (marked_for_deletion !== undefined) {
      renewal.marked_for_deletion = marked_for_deletion
      renewal.marked_for_deletion_at = marked_for_deletion ? new Date().toISOString() : null
    }

    if (notes !== undefined) {
      renewal.notes = notes
    }

    renewal.updated_at = new Date().toISOString()

    return NextResponse.json({ data: [renewal] })
  } catch (error) {
    console.error('Unexpected error:', error)
    return NextResponse.json(
      { error: 'Unexpected error', details: error },
      { status: 500 }
    )
  }
}
